version: '3.8'

services:
  omni-email:
    image: dhruvsharma983/map-my-email:latest
    container_name: omni-email
    env_file: .env
    restart: unless-stopped
    networks:
      - omni-network

  omni-whatsapp:
    image: dhruvsharma983/map-my-whatsapp:latest
    container_name: omni-whatsapp
    ports:
      - "3001:3001"
    env_file: .env
    restart: unless-stopped
    networks:
      - omni-network

  omni-backend:
    image: dhruvsharma983/wa-field-tracker:latest
    container_name: omni-backend
    ports:
      - "3000:3000"
    env_file: .env
    restart: unless-stopped
    depends_on:
      - omni-email
      - omni-whatsapp
    networks:
      - omni-network

  omni-ui:
    image: dhruvsharma983/wa-field-tracker-ui:latest
    container_name: omni-ui
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - omni-backend
    networks:
      - omni-network

networks:
  omni-network:
    driver: bridge
