-- Three-Agent Architecture — Phase A schema migration
-- Spec: docs/superpowers/specs/2026-05-11-three-agent-architecture.md
--
-- WARNING: this migration TRUNCATES nodes/edges and DROPs knowledge_maps.
-- Per the PRD's "don't backfill" decision, all legacy graph data is wiped.
-- Run in Supabase SQL editor as a single transaction so a partial failure
-- doesn't leave the schema half-migrated.

BEGIN;

-- 1. Wipe legacy graph state. agent_runs.graph_diff stays (audit history).
TRUNCATE TABLE nodes, edges CASCADE;
DROP TABLE IF EXISTS knowledge_maps;

-- 2. Scope columns on nodes/edges.
--    Default 'business' is safe: legacy rows are already gone, and any future
--    insert that forgets to specify the scope will land in the business graph
--    rather than silently polluting a random employee's comms graph.
ALTER TABLE nodes
  ADD COLUMN IF NOT EXISTS scope_type text NOT NULL DEFAULT 'business'
    CHECK (scope_type IN ('business','comms')),
  ADD COLUMN IF NOT EXISTS scope_employee_id bigint
    REFERENCES employees(id) ON DELETE CASCADE;

ALTER TABLE edges
  ADD COLUMN IF NOT EXISTS scope_type text NOT NULL DEFAULT 'business'
    CHECK (scope_type IN ('business','comms')),
  ADD COLUMN IF NOT EXISTS scope_employee_id bigint
    REFERENCES employees(id) ON DELETE CASCADE;

-- Sanity invariant: business-scope rows must NOT have an employee id; comms-scope must.
ALTER TABLE nodes
  ADD CONSTRAINT nodes_scope_consistent
    CHECK (
      (scope_type = 'business' AND scope_employee_id IS NULL)
      OR
      (scope_type = 'comms'    AND scope_employee_id IS NOT NULL)
    );

ALTER TABLE edges
  ADD CONSTRAINT edges_scope_consistent
    CHECK (
      (scope_type = 'business' AND scope_employee_id IS NULL)
      OR
      (scope_type = 'comms'    AND scope_employee_id IS NOT NULL)
    );

CREATE INDEX IF NOT EXISTS nodes_scope_idx
  ON nodes (scope_type, scope_employee_id);
CREATE INDEX IF NOT EXISTS edges_scope_idx
  ON edges (scope_type, scope_employee_id);

-- 3. Thread participants. Records which employees can see which threads.
--    The CommunicationsAgent upserts here for every message it processes.
CREATE TABLE IF NOT EXISTS thread_participants (
  id           bigint generated by default as identity primary key,
  channel      text   not null check (channel in ('email','whatsapp')),
  thread_id    text   not null,
  employee_id  bigint not null references employees(id) on delete cascade,
  joined_at    timestamptz not null default now(),
  unique (channel, thread_id, employee_id)
);

CREATE INDEX IF NOT EXISTS thread_participants_lookup_idx
  ON thread_participants (employee_id, channel, thread_id);

CREATE INDEX IF NOT EXISTS thread_participants_by_thread_idx
  ON thread_participants (channel, thread_id);

-- 4. Synthesis runs. Used for rate limiting + caching the on-demand endpoint.
CREATE TABLE IF NOT EXISTS synthesis_runs (
  id                bigint generated by default as identity primary key,
  employee_id       bigint references employees(id) on delete cascade,
  started_at        timestamptz not null default now(),
  completed_at      timestamptz,
  follow_ups_emitted int default 0,
  prompt_tokens     int,
  completion_tokens int,
  notes             text
);

CREATE INDEX IF NOT EXISTS synthesis_runs_recent_idx
  ON synthesis_runs (employee_id, started_at desc);

-- 5. Recursive downline function — returns the employee plus everyone
--    transitively reporting to them via employees.managedBy. Used by API
--    scope checks (see core/agents/scopeService.js).
CREATE OR REPLACE FUNCTION visible_employee_ids(p_employee_id bigint)
RETURNS TABLE (id bigint)
LANGUAGE sql
STABLE
AS $$
  WITH RECURSIVE downline AS (
    SELECT e.id FROM employees e WHERE e.id = p_employee_id
    UNION
    SELECT e.id
    FROM employees e
    JOIN downline d ON e."managedBy" = d.id
  )
  SELECT id FROM downline;
$$;

COMMIT;
