-- Refinement Agents — Phase A schema
-- Run in Supabase SQL editor.

-- 1. Job queue
CREATE TABLE IF NOT EXISTS public.agent_jobs (
  id              bigint generated by default as identity primary key,
  channel         text not null check (channel in ('email','whatsapp','business')),
  source_table    text not null,
  source_id       bigint,
  payload         jsonb not null,
  status          text not null default 'pending'
                  check (status in ('pending','running','done','failed')),
  attempts        int  not null default 0,
  last_error      text,
  created_at      timestamptz not null default now(),
  started_at      timestamptz,
  completed_at    timestamptz
);

CREATE INDEX IF NOT EXISTS agent_jobs_pending_idx
  ON public.agent_jobs (channel, created_at)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS agent_jobs_stale_running_idx
  ON public.agent_jobs (started_at)
  WHERE status = 'running';

-- 2. Follow-ups (proactive suggestions)
CREATE TABLE IF NOT EXISTS public.follow_ups (
  id              bigint generated by default as identity primary key,
  channel         text not null,
  source_job_id   bigint references public.agent_jobs(id) on delete set null,
  employee_id     bigint references public.employees(id),
  priority        text not null default 'normal'
                  check (priority in ('low','normal','high','urgent')),
  title           text not null,
  description     text,
  suggested_action text,
  related_node_ids bigint[],
  status          text not null default 'open'
                  check (status in ('open','dismissed','done')),
  created_at      timestamptz not null default now(),
  resolved_at     timestamptz
);

CREATE INDEX IF NOT EXISTS follow_ups_open_idx
  ON public.follow_ups (employee_id, status, created_at desc);

-- 3. Agent run audit (one row per agent execution)
CREATE TABLE IF NOT EXISTS public.agent_runs (
  id              bigint generated by default as identity primary key,
  job_id          bigint references public.agent_jobs(id) on delete cascade,
  agent_name      text not null,
  model           text,
  prompt_tokens   int,
  completion_tokens int,
  graph_diff      jsonb,
  follow_ups_emitted int default 0,
  duration_ms     int,
  notes           text,
  created_at      timestamptz not null default now()
);

CREATE INDEX IF NOT EXISTS agent_runs_by_job_idx
  ON public.agent_runs (job_id);
